#!/usr/bin/env bash
# Refresh api-reference/openapi.json from an open-source build of the core.
#
# The schema is generated by importing the FastAPI app, NOT by fetching
# /openapi.json from a running instance: apowerb.main removes /openapi.json,
# /docs and /redoc from the served routes ("[SCHEMA] not published" at boot),
# so a deployed instance has no schema endpoint to fetch.
#
# Importing the core alone also means the commercial bricks are absent by
# construction -- nothing to filter. The filter below stays as a guard, for the
# case where the interpreter's environment happens to have bricks installed.
#
# Usage:
#   ./scripts/sync-openapi.sh                       # uses python3 from PATH
#   ./scripts/sync-openapi.sh /path/to/core/.venv/bin/python
#
# The published version is read from the core's latest git tag, because
# pyproject.toml does not carry it: the release workflow injects the tag at
# build time, so the file itself stays at an old number. Override with
# APOWERB_VERSION when generating outside a clone of the core.
set -euo pipefail

PYTHON="${1:-python3}"
OUT="$(cd "$(dirname "$0")/.." && pwd)/api-reference/openapi.json"

if [[ -z "${APOWERB_VERSION:-}" ]]; then
  core_dir="$("$PYTHON" -c 'import apowerb, pathlib; print(pathlib.Path(apowerb.__file__).resolve().parent)' 2>/dev/null || true)"
  tag="$(git -C "${core_dir:-.}" describe --tags --abbrev=0 2>/dev/null || true)"
  APOWERB_VERSION="${tag#v}"
fi
if [[ -z "${APOWERB_VERSION:-}" ]]; then
  echo "cannot determine the core version: set APOWERB_VERSION=x.y.z" >&2
  exit 1
fi
export OUT APOWERB_VERSION

"$PYTHON" - <<'PY'
import json
import os

from apowerb.main import app

spec = app.openapi()

# Kept as a guard only: an open-source build has none of these. See
# concepts/editions.mdx for what each brick adds.
COMMERCIAL_TAGS = {"Billing", "usage", "prospection", "campaigns"}
COMMERCIAL_PATH_MARKERS = ("/mfa",)

# Identity-provider sign-in, added by the auth_advanced brick. The core's
# src/apowerb/users/router.py declares only /, /me, /{user_id} and
# /email/{user_email}.
COMMERCIAL_PATHS = {
    "/api/users/github",
    "/api/users/google",
    "/api/users/microsoft",
    "/api/users/linkedin",
}

removed = []
for path in list(spec["paths"]):
    tags = set()
    for _method, operation in spec["paths"][path].items():
        if isinstance(operation, dict):
            tags |= set(operation.get("tags", []))
    if (
        tags & COMMERCIAL_TAGS
        or path in COMMERCIAL_PATHS
        or any(m in path for m in COMMERCIAL_PATH_MARKERS)
    ):
        removed.append(path)
        del spec["paths"][path]

spec["info"] = {
    "title": "apowerb API",
    "description": "REST API of the apowerb agentic framework (open-source edition).",
    "version": os.environ["APOWERB_VERSION"],
    "license": {
        "name": "MIT",
        "url": "https://github.com/apowerb/apowerb/blob/main/LICENSE",
    },
}
spec["servers"] = [
    {"url": "https://api.example.com", "description": "Your apowerb instance"},
    {"url": "http://localhost:8000", "description": "Local stack"},
]

with open(os.environ["OUT"], "w") as handle:
    json.dump(spec, handle, indent=2, ensure_ascii=False)
    handle.write("\n")

print(
    f"{len(spec['paths'])} paths written at version {spec['info']['version']}"
    f", {len(removed)} commercial paths removed"
)
PY
